"""evento de uso

Revision ID: 027754aa533f
Revises: 2a3827c2a901
Create Date: 2026-09-23 19:51:40.140679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '027754aa533f'
down_revision: Union[str, Sequence[str], None] = '2a3827c2a901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento_uso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ruta', sa.String(length=128), nullable=False),
    sa.Column('tipo', sa.Enum('navegacion', 'accion', name='tipo_evento'), nullable=False),
    sa.Column('accion', sa.String(length=32), nullable=True),
    sa.Column('duracion_ms', sa.Integer(), nullable=False),
    sa.Column('estado_http', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evento_uso_fecha', 'evento_uso', ['creado_en'], unique=False)
    op.create_index('ix_evento_uso_usuario_fecha', 'evento_uso', ['user_id', 'creado_en'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evento_uso_usuario_fecha', table_name='evento_uso')
    op.drop_index('ix_evento_uso_fecha', table_name='evento_uso')
    op.drop_table('evento_uso')
    # ### end Alembic commands ###
    # Añadido a mano: `create_table` crea el tipo ENUM de Postgres, pero `drop_table` NO
    # lo borra. Sin esta línea, un downgrade seguido de upgrade falla con
    # `DuplicateObject: type "tipo_evento" already exists` (verificado en local).
    op.execute("DROP TYPE tipo_evento")
