"""jugador y mapeo de jugador

Revision ID: 13339aefec11
Revises: 43097a6bafa3
Create Date: 2026-08-27 14:30:03.619122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13339aefec11'
down_revision: Union[str, Sequence[str], None] = '43097a6bafa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('apodo', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('posicion', sa.String(length=32), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_mapping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('sitio', sa.String(length=64), nullable=False),
    sa.Column('id_externo', sa.String(length=64), nullable=False),
    sa.Column('nombre_externo', sa.String(length=255), nullable=False),
    sa.Column('origen', sa.Enum('heuristica', 'override_manual', name='origen_mapeo'), nullable=False),
    sa.Column('confianza', sa.Float(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'sitio', name='uq_player_mapping_jugador_sitio')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_mapping')
    op.drop_table('player')
    # ### end Alembic commands ###
