"""ejecucion de cron

Revision ID: 1a17fe9d3646
Revises: 027754aa533f
Create Date: 2026-09-24 08:46:39.492843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a17fe9d3646'
down_revision: Union[str, Sequence[str], None] = '027754aa533f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ejecucion_cron',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('iniciado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terminado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analitica_guardados', sa.Integer(), nullable=True),
    sa.Column('snapshot_resultado', sa.String(length=32), nullable=False),
    sa.Column('jugadores_escritos', sa.Integer(), nullable=True),
    sa.Column('con_analitica', sa.Integer(), nullable=True),
    sa.Column('sin_emparejar', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ejecucion_cron_inicio', 'ejecucion_cron', ['iniciado_en'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ejecucion_cron_inicio', table_name='ejecucion_cron')
    op.drop_table('ejecucion_cron')
    # ### end Alembic commands ###
