"""analitica diaria de todos los jugadores

Revision ID: 2a3827c2a901
Revises: f6f3741864a1
Create Date: 2026-08-28 14:26:09.354016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3827c2a901'
down_revision: Union[str, Sequence[str], None] = 'f6f3741864a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analitica_diaria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('id_externo', sa.String(length=32), nullable=False),
    sa.Column('nombre_externo', sa.String(length=255), nullable=False),
    sa.Column('equipo_externo', sa.String(length=16), nullable=False),
    sa.Column('tendencia_direccion', sa.String(length=16), nullable=True),
    sa.Column('tendencia_variacion_euros', sa.Integer(), nullable=True),
    sa.Column('media_diaria_euros', sa.Integer(), nullable=True),
    sa.Column('media_acumulada_euros', sa.Integer(), nullable=True),
    sa.Column('probabilidad_jugar', sa.Integer(), nullable=True),
    sa.Column('origen', sa.String(length=64), nullable=False),
    sa.Column('capturado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha', 'id_externo', name='uq_analitica_diaria_fecha_jugador')
    )
    op.create_index(op.f('ix_analitica_diaria_fecha'), 'analitica_diaria', ['fecha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analitica_diaria_fecha'), table_name='analitica_diaria')
    op.drop_table('analitica_diaria')
    # ### end Alembic commands ###
