"""snapshot de mercado

Revision ID: 5d8ba09d24cc
Revises: 13339aefec11
Create Date: 2026-08-27 14:39:50.149738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8ba09d24cc'
down_revision: Union[str, Sequence[str], None] = '13339aefec11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('valor_mercado', sa.Integer(), nullable=False),
    sa.Column('precio_venta', sa.Integer(), nullable=False),
    sa.Column('estado_jugador', sa.String(length=32), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analitica_estado', sa.Enum('disponible', 'unavailable', name='estado_analitica'), nullable=False),
    sa.Column('analitica_motivo', sa.String(length=255), nullable=True),
    sa.Column('analitica_origen', sa.String(length=64), nullable=True),
    sa.Column('analitica_capturado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tendencia_direccion', sa.String(length=16), nullable=True),
    sa.Column('tendencia_variacion_euros', sa.Integer(), nullable=True),
    sa.Column('probabilidad_jugar', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'fecha', name='uq_market_snapshot_jugador_fecha')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_snapshot')
    # ### end Alembic commands ###
