"""credenciales de laliga

Revision ID: f6f3741864a1
Revises: 5d8ba09d24cc
Create Date: 2026-08-28 09:27:31.294528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f3741864a1'
down_revision: Union[str, Sequence[str], None] = '5d8ba09d24cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laliga_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_cifrado', sa.LargeBinary(), nullable=False),
    sa.Column('password_cifrado', sa.LargeBinary(), nullable=False),
    sa.Column('refresh_token_cifrado', sa.LargeBinary(), nullable=True),
    sa.Column('ultimo_login_ok', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_error', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laliga_credentials')
    # ### end Alembic commands ###
